name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 17 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add upstream https://github.com/MAHA-Software-Engineering/NHTSA-Frontend.git
          git fetch upstream

      - name: Sync changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit
          git push origin main
